name: Deploy Notifier API

on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  IMAGE_NAME: ghcr.io/gurodrigues-dev/notifier-app
  COMMIT_SHA: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.5'

      - name: Get short SHA
        id: sha
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: docker build . --file Dockerfile.api --tag ${IMAGE_NAME}:latest --tag ${IMAGE_NAME}:${COMMIT_SHA}

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Publish docker image
        run: docker push --all-tags ${IMAGE_NAME}
